# input dir with fastq files
input:
    input_folder: '/primary/data/bazarova.el/fastq/test' 
    fastq_extensions: ['.fastq.gz', '.fq.gz'] 

output: '/primary/data/bazarova.el/fastq/results_containers'

reference: '/primary/data/bazarova.el/RNAseq/reference'

containers_path: '/primary/data/bazarova.el/RNAseq/singularity_containers'

to_trim: True

threads:
  fastqc: 2
  fastp: 4
  star_index: 8
  star: 12
  samtools: 8
  salmon: 8
  rustqc: 10

mem_mb:
   star: 40000 

star:
  read_length: 99

rustqc:
  params: '/primary/data/bazarova.el/RNAseq/config/rustqc.yaml'